# Generated by Django 4.2.7 on 2023-11-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chains', models.CharField(max_length=50, verbose_name='Название цепи')),
                ('gost_iso_din', models.CharField(choices=[('M GOST 588-81', 'M ГОСТ 588-81'), ('M ISO 1977', 'M ISO 1977'), ('MT ISO 1977', 'MT ISO 1977'), ('FV DIN', 'FV DIN'), ('FVТ DIN', 'FVТ DIN'), ('FVC DIN', 'FVC DIN'), ('Z DIN', 'Z DIN'), ('ZE DIN', 'ZE DIN'), ('ZC DIN', 'ZC DIN')], max_length=13, verbose_name='Код')),
                ('days', models.IntegerField(verbose_name='Дней доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLSKTSTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OtherVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=50, verbose_name='Брэнд цепи')),
                ('type_chain', models.CharField(max_length=3, verbose_name='Тип цепи')),
                ('km_field', models.FloatField()),
                ('pm_field', models.IntegerField(verbose_name='Дней')),
                ('mm_field', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_delivery', models.CharField(max_length=50, verbose_name='Тип доставки')),
            ],
        ),
        migrations.CreateModel(
            name='AllDeliveryTypeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_delivery', models.CharField(choices=[('LS', 'LR'), ('LT', 'LA')], max_length=3, verbose_name='Код')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('ratio', models.FloatField(verbose_name='Коэффициент')),
                ('id_name_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.typedelivery')),
            ],
        ),
    ]
