# Generated by Django 4.2.7 on 2023-11-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basechain',
            options={'verbose_name': 'Базовая цепь', 'verbose_name_plural': 'Базовые цепи'},
        ),
        migrations.AddField(
            model_name='basechain',
            name='weight',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='alldeliverytypeweight',
            name='code_delivery',
            field=models.CharField(choices=[('LS', 'LS'), ('LT', 'LT'), ('LR', 'LR'), ('LA', 'LA')], max_length=3, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='basechain',
            name='gost_iso_din',
            field=models.CharField(choices=[('MGOST', 'M ГОСТ 588-81'), ('MISO1977', 'M ISO 1977'), ('MTISO1977', 'MT ISO 1977'), ('FVDIN', 'FV DIN'), ('FVТDIN', 'FVТ DIN'), ('FVCDIN', 'FVC DIN'), ('ZDIN', 'Z DIN'), ('ZEDIN', 'ZE DIN'), ('ZCDIN', 'ZC DIN')], max_length=13, verbose_name='Стандарт'),
        ),
    ]
