# Generated by Django 4.2.7 on 2023-11-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_basechain_options_basechain_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basechain',
            name='weight',
            field=models.FloatField(),
        ),
    ]
