# Generated by Django 4.2.7 on 2023-11-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_basechain_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basechain',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
