# Generated by Django 4.2.7 on 2023-11-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_basechain_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basechain',
            name='days',
        ),
        migrations.AddField(
            model_name='basechain',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Коэффициент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basechain',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Вес'),
        ),
    ]
