# Generated by Django 4.2.7 on 2023-11-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_basechain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basechain',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ArticleID'),
        ),
    ]
