# Generated by Django 4.2.7 on 2023-11-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_alter_basechain_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=50, verbose_name='Брэнд цепи')),
            ],
        ),
        migrations.RemoveField(
            model_name='othervariant',
            name='km_field',
        ),
        migrations.RemoveField(
            model_name='othervariant',
            name='mm_field',
        ),
        migrations.RemoveField(
            model_name='othervariant',
            name='name_brand',
        ),
        migrations.RemoveField(
            model_name='othervariant',
            name='pm_field',
        ),
        migrations.RemoveField(
            model_name='othervariant',
            name='type_chain',
        ),
    ]
