# Generated by Django 4.2.7 on 2023-11-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_brandchain_remove_othervariant_km_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='othervariant',
            name='days',
            field=models.IntegerField(default=70, verbose_name='Дней на изготовление'),
        ),
        migrations.AddField(
            model_name='othervariant',
            name='id_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.brandchain'),
        ),
        migrations.AddField(
            model_name='othervariant',
            name='km_field',
            field=models.FloatField(default=1, verbose_name='Стоимость кг. дол. США'),
        ),
        migrations.AddField(
            model_name='othervariant',
            name='margin',
            field=models.FloatField(default=1, verbose_name='Маржа'),
        ),
        migrations.AddField(
            model_name='othervariant',
            name='type_processing',
            field=models.CharField(choices=[('NOP', 'без обработки'), ('ZN', 'оцинковка(ZN)'), ('NP', 'никелирование(NP)'), ('DR', 'горячая оцинковка(DR)'), ('GM', 'геомет(GM)'), ('SS', 'нержавейка(SS)')], default='NOP', max_length=30, verbose_name='Тип обработки цепи'),
        ),
    ]
