# Generated by Django 4.2.7 on 2023-11-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_othervariant_days_othervariant_id_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othervariant',
            old_name='id_brand',
            new_name='brand',
        ),
    ]
