# Generated by Django 4.2.7 on 2023-11-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_rename_id_brand_othervariant_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basechain',
            old_name='gost_iso_din',
            new_name='standard',
        ),
        migrations.AlterField(
            model_name='othervariant',
            name='type_processing',
            field=models.CharField(choices=[('NOP', 'без обработки'), ('ZN', 'оцинковка(ZN)'), ('NP', 'никелирование(NP)'), ('DR', 'горячая оцинковка(DR)'), ('GM', 'покрытие цепи геомет(GM)'), ('SS', 'нержавейка(SS)')], default='NOP', max_length=30, verbose_name='Тип обработки цепи'),
        ),
    ]
