# Generated by Django 4.2.7 on 2023-11-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_typedelivery_days_alter_typedelivery_code_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedelivery',
            name='days',
        ),
        migrations.AddField(
            model_name='typedelivery',
            name='duty',
            field=models.FloatField(default=300, verbose_name='Гос. пошлина у.е.'),
        ),
        migrations.CreateModel(
            name='DeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('rate', models.FloatField(default=0, verbose_name='Коэффициент')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('type_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.typedelivery')),
            ],
            options={
                'verbose_name': 'Стоимость доставки',
                'verbose_name_plural': 'Стоимость доставки',
            },
        ),
    ]
