# Generated by Django 4.2.7 on 2023-11-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_email_password',
            field=models.CharField(help_text='Введите пароль от вашего емейла', max_length=50, verbose_name='Пароль email для отправки сообщений'),
        ),
    ]
