# Generated by Django 4.2.7 on 2023-11-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_user_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_email_password',
            field=models.CharField(help_text='Введите пароль от вашего емейла', max_length=50, null=True, verbose_name='Пароль email для отправки сообщений'),
        ),
    ]
